### PR TITLE
Forward cookies

### PR DESCRIPTION
**Pull request by vikt0r0**
## Purpose

Allows for insertion of load-balancer between wallet-proxy endpoints. To facilitate this, user agents need to be able to include cookies in requests, and the wallet-proxy should forward these accordingly. Similarly, set-cookie headers should be retained in responses forwarded to client.

Depends on:

https://github.com/Concordium/concordium-client/pull/179

## Changes

- The wallet proxy extracts cookie headers from the user's initial (yesod) and includes them in the GRPC request.
- The wallet proxy extracts set-cookie headers from the GRPC response and includes them in the (yesod) response.
- In case the wallet proxy makes a chain of nested GRPC calls to serve the user request, set cookie headers that are received in a GRPC response is included in the next GRPC request. In this way, the wallet-proxy acts as a client.
- Added trace-level logging of cookies and headers that are sent and received.

## Checklist

- [X] My code follows the style of this project.
- [X] The code compiles without warnings.
- [X] I have performed a self-review of the changes.
- [X] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

**Comment by vikt0r0** [comment]
I have a bit of a concern regarding the ordering of cookies. According to the RFC, we should **not** rely on cookie orderings, but in case there are chained requests we repeatedly invoke "setHeader" with "set-cookie" headers, due to Web.Cookie not being able to parse expiry dates of set-cookie headers. I think ideally we should remove set-cookie headers and replace them by "fresh" ones in the yesod responses.

**Comment by abizjak** [comment]
Why was this closed?

**Comment by vikt0r0** [comment]
Using the Yesod cache turned out to be a much more viable option. I am just refactoring parts, will push a commit and reopen in a bit.

**Comment by vikt0r0** [comment]
I also tested the code with the following request-handlers, and it behaves as expected:

    getTest1R :: Handler TypedContent
    getTest1R = do
      _ <- runGRPC f $ \_ -> do
        _ <- runGRPC f $ \_ -> do
          sendResponse ()
        sendResponse ()
      sendResponse ()
      where f = return $ Left ""

    getTest2R :: Handler TypedContent
    getTest2R = do
      _ <- runGRPC f $ \_ -> return $ toTypedContent ()
      _ <- runGRPC f $ \_ -> return $ toTypedContent ()
      sendResponse ()
      where f = return $ Left ""

**Review by abizjak — APPROVED** [review]

**Pull request merged**
